### ISSUE TITLE
Hide totals

### ISSUE THREAD

**Issue by kaminskyelina** [BeamMW/android-wallet#176] opened 2019-03-31 09:39 UTC

**Comment by alexandrashelenkova** [comment] 2019-04-16 08:12
Duplicate of that issue https://github.com/BeamMW/android-wallet/issues/188

**Comment by sasha-abramovich** [comment] 2019-05-05 05:16
Closing as duplicate of https://github.com/BeamMW/android-wallet/issues/188
FYI: @gingervik

**Closed by sasha-abramovich** 2019-05-05 05:16 UTC
Labels: design
